# Site settings
author: Jesse kathryn
title: Fullstaq150
header-img: img/home-bg.png
email: jessekathrynbarnes@gmail.com
copyright_name: Jesse kathryn
description: > # this means to ignore newlines until "baseurl:"
  Ludlow Economy Candy
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jessekathryn

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
